In [1]:
import numpy as np

In [2]:
import time
a = [i for i in range(10000000)]
b = [i for i in range(10000000, 20000000)]
c = []
start = time.time()
for i in range(len(a)):
  c.append(a[i] + b[i])
print(time.time() - start)

2.749516487121582


In [3]:
a = np.arange(10000000)
b = np.arange(10000000, 20000000)
start = time.time()
c = a + b
print(time.time() - start)

0.13561010360717773


In [4]:
# It tells that numpy ndarrays are faster than python lists

In [5]:
import sys
a = [i for i in range(10000000)]
sys.getsizeof(a)

89095160

In [6]:
a = np.arange(10000000, dtype=np.int8)
sys.getsizeof(a)

10000112

# Advanced Indexing

In [7]:
a = np.arange(12).reshape(4, 3)
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [8]:
a[::2]

array([[0, 1, 2],
       [6, 7, 8]])

In [10]:
# Fancy indexing: We can directly put the indexes of the row we want and we will get them
a[[0, 2, 3]]

array([[ 0,  1,  2],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [11]:
a = np.arange(24).reshape(6, 4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [12]:
a[[0, 2, 3, 5]]

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [20, 21, 22, 23]])

In [13]:
a[:, [0, 2, 3]]

array([[ 0,  2,  3],
       [ 4,  6,  7],
       [ 8, 10, 11],
       [12, 14, 15],
       [16, 18, 19],
       [20, 22, 23]])

In [14]:
# Fancy indexing is used whenever we are unable to find pattern in indexing

In [16]:
a = np.random.randint(1, 100, 24).reshape(6, 4)
a

array([[20, 14, 45, 57],
       [29, 62, 88, 63],
       [43,  2, 21, 90],
       [92,  8, 88, 97],
       [12, 78, 87, 21],
       [48, 95, 90, 11]])

In [17]:
a > 50

array([[False, False, False,  True],
       [False,  True,  True,  True],
       [False, False, False,  True],
       [ True, False,  True,  True],
       [False,  True,  True, False],
       [False,  True,  True, False]])

In [18]:
# This is boolean masking
a[a > 50]

array([57, 62, 88, 63, 90, 92, 88, 97, 78, 87, 95, 90])

In [19]:
a[a % 2 == 0]

array([20, 14, 62, 88,  2, 90, 92,  8, 88, 12, 78, 48, 90])

In [20]:
# When working with booleans we should use & as it do the bitwise operations
a[(a > 50) & (a % 2 == 0)]

array([62, 88, 90, 92, 88, 78, 90])

In [21]:
a[a % 7 == 0]

array([14, 63, 21, 21])

# Broadcasting

In [22]:
a = np.arange(6).reshape(2, 3)
b = np.arange(6, 12).reshape(2, 3)

print(a + b)

print(a)
print(b)

[[ 6  8 10]
 [12 14 16]]
[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [23]:
a = np.arange(6).reshape(2, 3)
b = np.arange(3).reshape(1, 3)

print(a + b)

print(a)
print(b)

[[0 2 4]
 [3 5 7]]
[[0 1 2]
 [3 4 5]]
[[0 1 2]]


# Working with mathematical formulas

In [24]:
a = np.arange(10)
np.sin(a)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [25]:
def sigmoid(array):
  return 1 / (1 + np.exp(-array))

sigmoid(a)

array([0.5       , 0.73105858, 0.88079708, 0.95257413, 0.98201379,
       0.99330715, 0.99752738, 0.99908895, 0.99966465, 0.99987661])

In [26]:
def mse(actual, predicted):
  return np.mean((actual - predicted) ** 2)

actual = np.random.randint(1, 50, 25)
predicted = np.random.randint(1, 50, 25)

mse(actual, predicted)

np.float64(420.36)

In [27]:
def bce(actual, predicted_probability):
  log_p = np.log(predicted_probability)
  one_log_p = np.log(1 - predicted_probability)
  return -np.mean((actual * log_p) + ((1 - actual) * one_log_p))

actual = np.random.randint(0, 2, 25)
predicted = np.random.random(25)
bce(actual, predicted)

np.float64(0.8812128769831162)

# Working with missing values

In [28]:
# np.nan makes a missing or none value
a = np.array([1, 2, 3, 4, np.nan, 6])
a

array([ 1.,  2.,  3.,  4., nan,  6.])

In [29]:
# Both None in python and np.nan in numpy are considered as different things

In [30]:
# np.isnan() tells whether there is a nan value in the ndarray
a[~np.isnan(a)]

array([1., 2., 3., 4., 6.])