In [1]:
import numpy as np

In [3]:
# np.sort
# return a sorted copy of an array

In [4]:
a = np.random.randint(1, 100, 15)
a

array([ 3, 62, 62, 16, 97, 99, 83, 57, 67, 75,  6,  1, 39, 88, 96])

In [5]:
b = np.random.randint(1, 100, 24).reshape(6, 4)
b

array([[77, 53, 19, 77],
       [74, 59, 13, 77],
       [22, 31, 16, 35],
       [86, 93, 72, 86],
       [96,  6, 29, 61],
       [16, 44, 82, 77]])

In [6]:
# Gives the sorted array in ascending order
np.sort(a)

array([ 1,  3,  6, 16, 39, 57, 62, 62, 67, 75, 83, 88, 96, 97, 99])

In [7]:
# It will sort the 2D array in the row wise manner
np.sort(b)

array([[19, 53, 77, 77],
       [13, 59, 74, 77],
       [16, 22, 31, 35],
       [72, 86, 86, 93],
       [ 6, 29, 61, 96],
       [16, 44, 77, 82]])

In [8]:
# It will sort the 2D array in the column wise manner
np.sort(b, axis=0)

array([[16,  6, 13, 35],
       [22, 31, 16, 61],
       [74, 44, 19, 77],
       [77, 53, 29, 77],
       [86, 59, 72, 77],
       [96, 93, 82, 86]])

In [9]:
# To sort the array in the descending order we have to use this [::-1]
np.sort(a)[::-1]

array([99, 97, 96, 88, 83, 75, 67, 62, 62, 57, 39, 16,  6,  3,  1])

In [10]:
# np.append
# it appends values along the mentioned axis at the end of the array

In [11]:
a

array([ 3, 62, 62, 16, 97, 99, 83, 57, 67, 75,  6,  1, 39, 88, 96])

In [12]:
np.append(a, 200)

array([  3,  62,  62,  16,  97,  99,  83,  57,  67,  75,   6,   1,  39,
        88,  96, 200])

In [13]:
a

array([ 3, 62, 62, 16, 97, 99, 83, 57, 67, 75,  6,  1, 39, 88, 96])

In [14]:
b

array([[77, 53, 19, 77],
       [74, 59, 13, 77],
       [22, 31, 16, 35],
       [86, 93, 72, 86],
       [96,  6, 29, 61],
       [16, 44, 82, 77]])

In [15]:
np.append(b, np.ones((b.shape[0], 1)), axis=1)

array([[77., 53., 19., 77.,  1.],
       [74., 59., 13., 77.,  1.],
       [22., 31., 16., 35.,  1.],
       [86., 93., 72., 86.,  1.],
       [96.,  6., 29., 61.,  1.],
       [16., 44., 82., 77.,  1.]])