In [2]:
import numpy as np

oneDArray = np.array([1, 2, 3])

print(oneDArray)
print(type(oneDArray))

[1 2 3]
<class 'numpy.ndarray'>


In [3]:

twoDArray = np.array([[1, 2, 3], [4, 5, 6]])

print(twoDArray)

[[1 2 3]
 [4 5 6]]


In [4]:
threeDArray = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

print(threeDArray)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [5]:
# dtype means datatype of the values/items inside the array
floatTypeArray = np.array([1, 2, 3], dtype=float) # This is the float type array

boolTypeArray = np.array([1, 2, 3], dtype=bool) # This is the boolean type array

print(floatTypeArray)
print(boolTypeArray)

[1. 2. 3.]
[ True  True  True]


In [6]:
np.arange(1, 11) # Creates an ndarray (n dimensional array) starting from 1 to 10 as 11 is excluded [1, 11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
np.arange(1, 11, 2) # Creates an ndarray from 1 to 10 but there is skip of 2

array([1, 3, 5, 7, 9])

In [8]:
withoutReshapeArray = np.arange(1, 11) # Shape is 1 x 10
print(withoutReshapeArray)

reshapedArray = withoutReshapeArray.reshape(5, 2) # Shape is 5 x 2
print(reshapedArray)
# It will only reshape if the reshaping is possible like the array which we want to reshape should be having the number of items = the reshape rows and columns
# For e.g we are having 10 values inside the withoutReshapeArray and we want to reshape to 5 x 2, so 10 = 5 * 2, so reshaping is possible

[ 1  2  3  4  5  6  7  8  9 10]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


In [9]:
np.arange(1, 11).reshape(5, 2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [10]:
np.arange(1, 11).reshape(2, 5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [11]:
np.ones((3, 4)) # If we want to create a n x m ndarray then we have to pass a tuple inside the function

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [12]:
np.zeros(3) # If we want to create a vector or 1 x n zeros ndarray of items 0 so you should only give the columns size like here we have given 3 so it is 1 x 3 ndarray

array([0., 0., 0.])

In [13]:
np.random.random((3, 4)) # It will generate a ndarray of items from 0 to 1 of the size you have passed in the tuple
# The range of the random will be from [0, 1) -> 1 excluded, 0 included

array([[0.06575086, 0.30185787, 0.35269189, 0.4743008 ],
       [0.16894436, 0.79590616, 0.7462274 , 0.63610078],
       [0.17790753, 0.90771043, 0.89105712, 0.05767997]])

In [14]:
np.linspace(-10, 10, 10) # It will generate a ndarray of size 10 (the third parameter) from range starting from -10 to ending point 10
# It will generate 10 number of items in a ndarray and each point will be of same distance

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [15]:
np.linspace(-1, 10, 20)
# The full form of linspace is linear space
# Every point distance will be same in the linspace

array([-1.        , -0.42105263,  0.15789474,  0.73684211,  1.31578947,
        1.89473684,  2.47368421,  3.05263158,  3.63157895,  4.21052632,
        4.78947368,  5.36842105,  5.94736842,  6.52631579,  7.10526316,
        7.68421053,  8.26315789,  8.84210526,  9.42105263, 10.        ])

In [16]:
np.identity(3)
# It will create an identity matrix of size 3 x 3

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# Array Attributes

In [17]:
a1 = np.arange(10)
a2 = np.arange(12, dtype=float).reshape(3, 4)
a3 = np.arange(8).reshape(2, 2, 2)

In [18]:
# ndim tells about the dimension of the ndarray, it's fullform is Number Of Dimensions
print(a1.ndim) # 1D Array -> Vector
print(a2.ndim) # 2D Array -> Matrix
print(a3.ndim) # 3D Array -> Tensor

1
2
3


In [19]:
# shape tells us about the shape of the given ndarray
print(a1.shape) # (10,) as it has 10 columns no rows
print(a2.shape) # (3, 4) as it has 3 rows 4 columns
print(a3.shape) # (2, 2, 2) as it has 2 2D arrays each having 2 rows and 2 columns

(10,)
(3, 4)
(2, 2, 2)


In [20]:
# size tells us how many items are there in a ndarray
print(a1.size)
print(a2.size)
print(a3.size)

10
12
8


In [21]:
# itemsize tells us about the size of one array item in bytes like how much bytes of size is taken by one item of the ndarray
print(a1.itemsize)
print(a2.itemsize)
print(a3.itemsize)
# Here all 3 ndarrays are giving 8 itemsize as the default int is int64 is of 8 bytes of size

8
8
8


In [22]:
# dtype will give you the datatype of items in the ndarray
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int64
float64
int64


# Changing Datatypes

In [23]:
a3.dtype

dtype('int64')

In [24]:
# astype changes the datatype of all the items of the ndarray
a3 = a3.astype(np.int32)

In [25]:
a3.dtype

dtype('int32')

In [26]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

# Array Operations

In [27]:
a1 = np.arange(12).reshape(3, 4)
a2 = np.arange(12, 24).reshape(3, 4)

In [28]:
a1 * 2

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [29]:
# Will check this operation for each item in the ndarray a2 and then tell whether for each item in the array that the operation or check is true or not
a2 > 18

array([[False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True]])

In [30]:
a2 == 18

array([[False, False, False, False],
       [False, False,  True, False],
       [False, False, False, False]])

In [31]:
# Vector operations as the size of a1 and a2 are same hence we can do the vector operations for ndarray
a1 + a2

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [32]:
a1, a2

(array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]))

In [33]:
# It will raise the power of corresponding item of the a2 to the a1
a1 ** a2

array([[                   0,                    1,                16384,
                    14348907],
       [          4294967296,         762939453125,      101559956668416,
           11398895185373143],
       [ 1152921504606846976, -1261475310744950487,  1864712049423024128,
         6839173302027254275]])

# Array Functions

In [36]:
a1 = np.random.random((3, 3))
a1 = np.round(a1 * 100)
a1

array([[27., 82., 73.],
       [72., 25., 60.],
       [59.,  1., 49.]])

In [37]:
np.max(a1)

np.float64(82.0)

In [38]:
np.min(a1)

np.float64(1.0)

In [39]:
# Will give the sum of all the items in a1 ndarray
np.sum(a1)

np.float64(448.0)

In [40]:
# Will give the product of all the items in a1 ndarray
np.prod(a1)

np.float64(50462913816000.0)

In [41]:
# axis = 0 means that we are doing it for column, so for each column it gives us the min item in a1 ndarray
np.min(a1, axis=0)

array([27.,  1., 49.])

In [42]:
# axis = 1 means that we are doing it for row, so for each row it gives us the min item in a1 ndarray
np.min(a1, axis=1)

array([27., 25.,  1.])

In [43]:
# axis = 1 means row
# axis = 0 means column

In [44]:
# It will calculate the mean for all items in the ndarray
np.mean(a1)

np.float64(49.77777777777778)

In [45]:
np.mean(a1) == np.sum(a1) / a1.size

np.True_

In [46]:
# It will give us the mean of a1 matrix column wise
np.mean(a1, axis=0)

array([52.66666667, 36.        , 60.66666667])

In [47]:
np.mean(a1, axis=0) == np.sum(a1, axis=0) / np.size(a1, axis=0)

array([ True,  True,  True])

In [48]:
np.size(a1, axis=0)

3

In [49]:
# Median
np.median(a1)

np.float64(59.0)

In [50]:
# Standard deviation
np.std(a1, axis=0)

array([18.90913947, 33.9705755 ,  9.80929265])

In [51]:
np.var(a1)

np.float64(641.5061728395062)

In [52]:
# Whenever we are taking dot product of two matrices so the columns of the first matrix should be equal to the rows of the second matrix
a1 = np.arange(12).reshape(3, 4)
a2 = np.arange(12, 24).reshape(4, 3)
# Here the a1 matrix has 3 x 4 and a2 matrix has 4 x 3 so the resultant matrix has shape of 3 x 3
np.dot(a1, a2)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [53]:
a1 = np.random.random((3, 4)) * 100
a1

array([[34.79347575, 96.76407672, 24.573852  , 46.84982004],
       [63.36284003, 31.98834877, 45.79197472, 28.56752742],
       [79.94022853, 72.08093882,  1.02812239, 52.59277624]])

In [54]:
# log is used to take log of each item in the ndarray
np.log(a1)

array([[3.54942989, 4.57227582, 3.20168295, 3.84694717],
       [4.14887757, 3.46537174, 3.82410885, 3.35227067],
       [4.38127921, 4.27778964, 0.02773421, 3.96257878]])

In [55]:
# exp is used to calculate the exponent of each item in the ndarray
np.exp(a1)

array([[1.29007371e+15, 1.05707199e+42, 4.70206167e+10, 2.22135680e+20],
       [3.29709746e+27, 7.80482832e+13, 7.71262003e+19, 2.55105323e+12],
       [5.21915427e+34, 2.01536623e+31, 2.79581145e+00, 6.93030756e+22]])

In [56]:
# round takes the round for each item in the ndarray
np.round(np.random.random((2, 3)) * 100)

array([[ 40.,  45.,  30.],
       [100.,   1.,  99.]])

In [57]:
# floor takes the floor for each item in the ndarray
# e.g 3.4 -> 3 it takes the lower value of the float
np.floor(np.random.random((2, 3)) * 100)

array([[93., 35., 43.],
       [ 0., 57., 45.]])

In [58]:
# ceil takes the ceil for each item in the ndarray
# e.g 3.4 -> 4 it takes the higher value of the float
np.ceil(np.random.random((2, 3)) * 100)

array([[65., 18., 89.],
       [94., 55., 50.]])

# Indexing And Slicing

In [59]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3, 4)
a3 = np.arange(8).reshape(2, 2, 2)

In [60]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [61]:
a1[-1]

np.int64(9)

In [62]:
a1[0]

np.int64(0)

In [63]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [64]:
a2[0]

array([0, 1, 2, 3])

In [65]:
a2[1, 2]

np.int64(6)

In [66]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [67]:
a3[1, 0, 1]

np.int64(5)

In [68]:
a3[0, 0, 0]

np.int64(0)

In [69]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [70]:
a1[2:5] # last index is not included, so items at 2-4th index will be sliced

array([2, 3, 4])

In [71]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [72]:
a2[0, :]

array([0, 1, 2, 3])

In [73]:
a2[:, 2]

array([ 2,  6, 10])

In [74]:
a2[1:, 1:3]

array([[ 5,  6],
       [ 9, 10]])

In [75]:
a2[::2, ::3]

array([[ 0,  3],
       [ 8, 11]])

In [76]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [77]:
a3 = np.arange(27).reshape(3, 3, 3)

In [78]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [79]:
a3[1]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [80]:
a3[::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [81]:
a3[0, 1]

array([3, 4, 5])