In [1]:
import numpy as np

In [3]:
# np.sort
# return a sorted copy of an array

In [4]:
a = np.random.randint(1, 100, 15)
a

array([ 3, 62, 62, 16, 97, 99, 83, 57, 67, 75,  6,  1, 39, 88, 96])

In [5]:
b = np.random.randint(1, 100, 24).reshape(6, 4)
b

array([[77, 53, 19, 77],
       [74, 59, 13, 77],
       [22, 31, 16, 35],
       [86, 93, 72, 86],
       [96,  6, 29, 61],
       [16, 44, 82, 77]])

In [6]:
# Gives the sorted array in ascending order
np.sort(a)

array([ 1,  3,  6, 16, 39, 57, 62, 62, 67, 75, 83, 88, 96, 97, 99])

In [7]:
# It will sort the 2D array in the row wise manner
np.sort(b)

array([[19, 53, 77, 77],
       [13, 59, 74, 77],
       [16, 22, 31, 35],
       [72, 86, 86, 93],
       [ 6, 29, 61, 96],
       [16, 44, 77, 82]])

In [8]:
# It will sort the 2D array in the column wise manner
np.sort(b, axis=0)

array([[16,  6, 13, 35],
       [22, 31, 16, 61],
       [74, 44, 19, 77],
       [77, 53, 29, 77],
       [86, 59, 72, 77],
       [96, 93, 82, 86]])

In [9]:
# To sort the array in the descending order we have to use this [::-1]
np.sort(a)[::-1]

array([99, 97, 96, 88, 83, 75, 67, 62, 62, 57, 39, 16,  6,  3,  1])

In [10]:
# np.append
# it appends values along the mentioned axis at the end of the array

In [11]:
a

array([ 3, 62, 62, 16, 97, 99, 83, 57, 67, 75,  6,  1, 39, 88, 96])

In [12]:
np.append(a, 200)

array([  3,  62,  62,  16,  97,  99,  83,  57,  67,  75,   6,   1,  39,
        88,  96, 200])

In [13]:
a

array([ 3, 62, 62, 16, 97, 99, 83, 57, 67, 75,  6,  1, 39, 88, 96])

In [14]:
b

array([[77, 53, 19, 77],
       [74, 59, 13, 77],
       [22, 31, 16, 35],
       [86, 93, 72, 86],
       [96,  6, 29, 61],
       [16, 44, 82, 77]])

In [15]:
np.append(b, np.ones((b.shape[0], 1)), axis=1)

array([[77., 53., 19., 77.,  1.],
       [74., 59., 13., 77.,  1.],
       [22., 31., 16., 35.,  1.],
       [86., 93., 72., 86.,  1.],
       [96.,  6., 29., 61.,  1.],
       [16., 44., 82., 77.,  1.]])

In [16]:
# np.concatenate
# it concatenate a sequence of arrays along an exisiting axis

In [17]:
c = np.arange(6).reshape(2, 3)
d = np.arange(6, 12).reshape(2, 3)

In [18]:
print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [19]:
np.concatenate((c, d), axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [20]:
np.concatenate((c, d), axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

In [21]:
# np.unique
# it can give us the unique values from an array

In [22]:
e = np.array([1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6])

In [23]:
np.unique(e)

array([1, 2, 3, 4, 5, 6])

In [24]:
# np.expand_dims
# it can expand dimensions of an array

In [25]:
a

array([ 3, 62, 62, 16, 97, 99, 83, 57, 67, 75,  6,  1, 39, 88, 96])

In [26]:
np.expand_dims(a, axis=0)

array([[ 3, 62, 62, 16, 97, 99, 83, 57, 67, 75,  6,  1, 39, 88, 96]])

In [27]:
np.expand_dims(a, axis=1)

array([[ 3],
       [62],
       [62],
       [16],
       [97],
       [99],
       [83],
       [57],
       [67],
       [75],
       [ 6],
       [ 1],
       [39],
       [88],
       [96]])

In [28]:
# np.where
# it returns the indices of the element where the given conditions gets setisfied

In [29]:
# It gives the index position of all the elements of array a where a > 50
np.where(a > 50)

(array([ 1,  2,  4,  5,  6,  7,  8,  9, 13, 14]),)

In [30]:
# Firstly we gives the condition then what if the statement is true and next we give what if the condition is not satisfying
np.where(a > 50, a, 0)

array([ 0, 62, 62,  0, 97, 99, 83, 57, 67, 75,  0,  0,  0, 88, 96])

In [31]:
np.where(a % 2 == 0, 0, a)

array([ 3,  0,  0,  0, 97, 99, 83, 57, 67, 75,  0,  1, 39,  0,  0])

In [32]:
# np.argmax
# it gives the index of the max element of the array in a particular axis

In [33]:
a

array([ 3, 62, 62, 16, 97, 99, 83, 57, 67, 75,  6,  1, 39, 88, 96])

In [34]:
# Giving the index of the max element in the array a
np.argmax(a)

np.int64(5)

In [35]:
b

array([[77, 53, 19, 77],
       [74, 59, 13, 77],
       [22, 31, 16, 35],
       [86, 93, 72, 86],
       [96,  6, 29, 61],
       [16, 44, 82, 77]])

In [36]:
# Gives the index of the max element in each column
np.argmax(b, axis=0)

array([4, 3, 5, 3])

In [37]:
np.argmax(b, axis=1)

array([0, 3, 3, 1, 0, 2])

In [38]:
# Gives the index of the minimum value inside the array a
np.argmin(a)

np.int64(11)

In [39]:
# np.cumsum
# it is used when we want to compute the cumulative sum of array element over a given axis

In [40]:
np.cumsum(b, axis=0)

array([[ 77,  53,  19,  77],
       [151, 112,  32, 154],
       [173, 143,  48, 189],
       [259, 236, 120, 275],
       [355, 242, 149, 336],
       [371, 286, 231, 413]])

In [41]:
b

array([[77, 53, 19, 77],
       [74, 59, 13, 77],
       [22, 31, 16, 35],
       [86, 93, 72, 86],
       [96,  6, 29, 61],
       [16, 44, 82, 77]])

In [42]:
# It will cumsum the array b row wise
np.cumsum(b, axis=1)

array([[ 77, 130, 149, 226],
       [ 74, 133, 146, 223],
       [ 22,  53,  69, 104],
       [ 86, 179, 251, 337],
       [ 96, 102, 131, 192],
       [ 16,  60, 142, 219]])

In [43]:
# It will give the cumulative product of the array a
np.cumprod(a)

array([                   3,                  186,                11532,
                     184512,             17897664,           1771868736,
               147065105088,        8382710990016,      561641636331072,
          42123122724830400,   252738736348982400,   252738736348982400,
       -8589933356099238016,   402371685358670848,  1734193647013298176])

In [44]:
# np.precentile
# it is used to compute the nth percentile of the array elements along a given axis

In [45]:
a

array([ 3, 62, 62, 16, 97, 99, 83, 57, 67, 75,  6,  1, 39, 88, 96])

In [46]:
np.percentile(a, 100)

np.float64(99.0)

In [47]:
np.percentile(a, 0)

np.float64(1.0)

In [48]:
np.percentile(a, 50)

np.float64(62.0)

In [49]:
np.median(a)

np.float64(62.0)

In [50]:
# np.histogram
# it represents the frequency of the data distribution in the graphical form 

In [51]:
a

array([ 3, 62, 62, 16, 97, 99, 83, 57, 67, 75,  6,  1, 39, 88, 96])

In [52]:
np.histogram(a, bins=[0, 10, 20, 30, 40, 50, 60, 70, 80, 90, 100])

(array([3, 1, 0, 1, 0, 1, 3, 1, 2, 3]),
 array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100]))

In [53]:
# np.corrcoef
# it returns pearson product-moment correlation coefficient

In [54]:
salary = np.array([20000, 40000, 25000, 35000, 60000])
experience = np.array([1, 3, 2, 4, 2])

In [55]:
salary = np.array([20000, 40000, 25000, 35000, 60000])
experience = np.array([1, 3, 2, 4, 2])

np.corrcoef(salary, experience)

array([[1.        , 0.25344572],
       [0.25344572, 1.        ]])

In [56]:
# np.isin
# we can search multiple items from the array
items = [10, 20, 30, 40, 50, 60, 70, 80, 90, 100]
np.isin(a, items)

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False])

In [57]:
# np.flip
# it reverses the order of array elements along the specified axis, preserving the shape of the array
np.flip(a)

array([96, 88, 39,  1,  6, 75, 67, 57, 83, 99, 97, 16, 62, 62,  3])

In [58]:
b

array([[77, 53, 19, 77],
       [74, 59, 13, 77],
       [22, 31, 16, 35],
       [86, 93, 72, 86],
       [96,  6, 29, 61],
       [16, 44, 82, 77]])

In [59]:
np.flip(b, axis=1)

array([[77, 19, 53, 77],
       [77, 13, 59, 74],
       [35, 16, 31, 22],
       [86, 72, 93, 86],
       [61, 29,  6, 96],
       [77, 82, 44, 16]])

In [60]:
np.flip(b)

array([[77, 82, 44, 16],
       [61, 29,  6, 96],
       [86, 72, 93, 86],
       [35, 16, 31, 22],
       [77, 13, 59, 74],
       [77, 19, 53, 77]])

In [61]:
# np.put
# it replaces the specific elements of an array with given values of p_array
a

array([ 3, 62, 62, 16, 97, 99, 83, 57, 67, 75,  6,  1, 39, 88, 96])

In [62]:
np.put(a, [0, 1], [230, 50])
a

array([230,  50,  62,  16,  97,  99,  83,  57,  67,  75,   6,   1,  39,
        88,  96])

In [63]:
# np.delete
# it returns the new array with the deletion of sub-arrays along with the mentioned axis
a

array([230,  50,  62,  16,  97,  99,  83,  57,  67,  75,   6,   1,  39,
        88,  96])

In [64]:
np.delete(a,  0)

array([50, 62, 16, 97, 99, 83, 57, 67, 75,  6,  1, 39, 88, 96])

In [65]:
np.delete(a, [0, 2, 4])

array([50, 16, 99, 83, 57, 67, 75,  6,  1, 39, 88, 96])

In [66]:
m = np.array([1, 2, 3, 4, 5])
n = np.array([3, 4, 5, 6, 7])

np.union1d(m, n)

array([1, 2, 3, 4, 5, 6, 7])

In [67]:
np.intersect1d(m, n)

array([3, 4, 5])

In [68]:
np.setdiff1d(m, n)

array([1, 2])

In [69]:
np.setxor1d(m, n)

array([1, 2, 6, 7])