In [2]:
import numpy as np

oneDArray = np.array([1, 2, 3])

print(oneDArray)
print(type(oneDArray))

[1 2 3]
<class 'numpy.ndarray'>


In [3]:

twoDArray = np.array([[1, 2, 3], [4, 5, 6]])

print(twoDArray)

[[1 2 3]
 [4 5 6]]


In [4]:
threeDArray = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

print(threeDArray)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [5]:
# dtype means datatype of the values/items inside the array
floatTypeArray = np.array([1, 2, 3], dtype=float) # This is the float type array

boolTypeArray = np.array([1, 2, 3], dtype=bool) # This is the boolean type array

print(floatTypeArray)
print(boolTypeArray)

[1. 2. 3.]
[ True  True  True]


In [6]:
np.arange(1, 11) # Creates an ndarray (n dimensional array) starting from 1 to 10 as 11 is excluded [1, 11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
np.arange(1, 11, 2) # Creates an ndarray from 1 to 10 but there is skip of 2

array([1, 3, 5, 7, 9])

In [8]:
withoutReshapeArray = np.arange(1, 11) # Shape is 1 x 10
print(withoutReshapeArray)

reshapedArray = withoutReshapeArray.reshape(5, 2) # Shape is 5 x 2
print(reshapedArray)
# It will only reshape if the reshaping is possible like the array which we want to reshape should be having the number of items = the reshape rows and columns
# For e.g we are having 10 values inside the withoutReshapeArray and we want to reshape to 5 x 2, so 10 = 5 * 2, so reshaping is possible

[ 1  2  3  4  5  6  7  8  9 10]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


In [9]:
np.arange(1, 11).reshape(5, 2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [10]:
np.arange(1, 11).reshape(2, 5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [11]:
np.ones((3, 4)) # If we want to create a n x m ndarray then we have to pass a tuple inside the function

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [12]:
np.zeros(3) # If we want to create a vector or 1 x n zeros ndarray of items 0 so you should only give the columns size like here we have given 3 so it is 1 x 3 ndarray

array([0., 0., 0.])

In [13]:
np.random.random((3, 4)) # It will generate a ndarray of items from 0 to 1 of the size you have passed in the tuple
# The range of the random will be from [0, 1) -> 1 excluded, 0 included

array([[0.42141129, 0.64251176, 0.89785077, 0.24924003],
       [0.79739913, 0.56642066, 0.8838638 , 0.30155382],
       [0.83294019, 0.85731564, 0.09487822, 0.66649248]])

In [14]:
np.linspace(-10, 10, 10) # It will generate a ndarray of size 10 (the third parameter) from range starting from -10 to ending point 10
# It will generate 10 number of items in a ndarray and each point will be of same distance

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [15]:
np.linspace(-1, 10, 20)
# The full form of linspace is linear space
# Every point distance will be same in the linspace

array([-1.        , -0.42105263,  0.15789474,  0.73684211,  1.31578947,
        1.89473684,  2.47368421,  3.05263158,  3.63157895,  4.21052632,
        4.78947368,  5.36842105,  5.94736842,  6.52631579,  7.10526316,
        7.68421053,  8.26315789,  8.84210526,  9.42105263, 10.        ])

In [16]:
np.identity(3)
# It will create an identity matrix of size 3 x 3

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# Array Attributes

In [17]:
a1 = np.arange(10)
a2 = np.arange(12, dtype=float).reshape(3, 4)
a3 = np.arange(8).reshape(2, 2, 2)

In [18]:
# ndim tells about the dimension of the ndarray, it's fullform is Number Of Dimensions
print(a1.ndim) # 1D Array -> Vector
print(a2.ndim) # 2D Array -> Matrix
print(a3.ndim) # 3D Array -> Tensor

1
2
3


In [19]:
# shape tells us about the shape of the given ndarray
print(a1.shape) # (10,) as it has 10 columns no rows
print(a2.shape) # (3, 4) as it has 3 rows 4 columns
print(a3.shape) # (2, 2, 2) as it has 2 2D arrays each having 2 rows and 2 columns

(10,)
(3, 4)
(2, 2, 2)


In [20]:
# size tells us how many items are there in a ndarray
print(a1.size)
print(a2.size)
print(a3.size)

10
12
8


In [21]:
# itemsize tells us about the size of one array item in bytes like how much bytes of size is taken by one item of the ndarray
print(a1.itemsize)
print(a2.itemsize)
print(a3.itemsize)
# Here all 3 ndarrays are giving 8 itemsize as the default int is int64 is of 8 bytes of size

8
8
8


In [22]:
# dtype will give you the datatype of items in the ndarray
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int64
float64
int64


# Changing Datatypes

In [23]:
a3.dtype

dtype('int64')

In [24]:
# astype changes the datatype of all the items of the ndarray
a3 = a3.astype(np.int32)

In [25]:
a3.dtype

dtype('int32')

In [26]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)